### PR TITLE
USDA Partitions Uploaded

### PR DESCRIPTION
**Pull request by JasonZhangzy1757**

### CODE REVIEW

**Review by ceteri — CHANGES_REQUESTED** [review]
Hi Jason, there was a legit merge conflict: two PRs adding the same new dataset. To resolve it, we're having the earlier definition supercede.  Could you please update these references so that:
`dataset-919` => `dataset-905` ?

Many thanks,
Paco

**Comment by JasonZhangzy1757** [comment]
Ah, Now I get why the pull request in RCDataset can't merge automatically. No problem! I'll do it as soon as possible!

**Comment by JasonZhangzy1757** [comment]
@ceteri  I just updated the ref in the partition. Do I understand you correctly?

**Review by ceteri — APPROVED** [review]
great, thank you very much for the updates

**Pull request merged**
