### PR TITLE
Sea Level Rise Data

### PR DESCRIPTION
**Pull request by JasonZhangzy1757**
This partition also includes 20191223_dimensions_Sea_Level_Rise_Inundation

### CODE REVIEW

**Review by ceteri — CHANGES_REQUESTED** [review]
The unit tests were failing when I tried to evaluate this PR. One of the files `20191119_SurveyofIncomeandProgramParticipation_publications.json` had been corrupted and couldn't be read as JSON. When I reworked the unit tests to show that condition more accurately, there were several partitions missing from this commit:

> 20191119_UnemploymentInsurancewagedata_publications.json
> 20191119_VermontUnemploymentInsurance_publications.json
> 20191119_VirginiaUnemploymentInsurance_publications.json
> 20191119_VocationalRehabilitationInitiative_publications.json
> 20191119_WashingtonUnemploymentInsurance_publications.json
> 20191119_WisconsinClientAssistanceforRe-employmentandEconomicSupport_publications.json
> 20191119_WisconsinDepartmentofCorrections_publications.json
> 20191119_WisconsinTemporaryAssistanceforNeedyFamilies_publications.json
> 20191119_WisconsinUnemploymentInsurance_publications.json
> 20191119_WisconsinWorks_W-2_publications.json
> 20191119_Women,Infants,andChildren_publications.json
> 20191119_WomensEmploymentStudy_publications.json
> 20191119_WorkforceInvestmentActStandardizedRecordData_publications.json
> 20191119_decisionsupportsystem_publications.json
> 20191125_SurveyofDoctorateRecipients_publications.json
> 20191206_ncses_publications.json
> 20191231_noaa_manual_sbr.json

I really have no idea what happened. Let me get this recorded into the PR comment history, then look further at the commit history.

**Comment by ceteri** [comment]
Hi @JasonZhangzy1757,  I looked into the commit history. Still not sure what happened. Some of the other files included in this PR seemed to be rather old -- for example, it was using a much older copy of `test.py` and `.gitignore`.

I took the `master` branch then added your new partition, plus my update on the unit tests.  That was merged already in PR #52 -- so this PR should be deleted.

**Comment by ceteri** [comment]
Also, it's probably a really good idea at this point to go through and run
```
git checkout master
git pull
```
on your repo, or delete and clone a new copy?

**Comment by JasonZhangzy1757** [comment]
I just realized I made such a silly mistake. I shouldn't upload the file directly to my branch instead of keeping my git updated and using git push. That's probably why all the other files are old. Thank you so much and sorry for the trouble!

**Comment by ceteri** [comment]
No worries, great to troubleshoot that!

**Pull request closed without merging**
